name: soia
description: A Dart client library for Soia serialization
version: 0.2.7
homepage: https://github.com/gepheum/soia-dart-client
repository: https://github.com/gepheum/soia-dart-client

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  http: ^1.1.0
  convert: ^3.0.0
  typed_data: ^1.3.2
  collection: ^1.19.1

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0

topics:
  - serialization
  - soia
  - json
  - binary
